SHOW DATABASES;
USE MYDATA;

-- 예제 데이터 생성
CREATE TABLE MYTABLE(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    MODELNUMBER VARCHAR(15) NOT NULL,
    SERIES VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID)
);
SHOW TABLES;
DESC MYTABLE;

-- 테이블 컬럼 수정
ALTER TABLE MYTABLE MODIFY COLUMN NAME VARCHAR(20) NOT NULL;
ALTER TABLE MYTABLE CHANGE COLUMN MODELNUMBER model_number VARCHAR(10) NOT NULL;
ALTER TABLE MYTABLE CHANGE COLUMN SERIES model_type VARCHAR(10) NOT NULL;
DESC MYTABLE;

DROP TABLE MYTABLE;
SHOW TABLES;


CREATE TABLE MY_TABLE_NEW(
	ID INT unsigned NOT NULL auto_increment,
    name varchar(20) not null,
    model_num varchar(10) not null,
    model_type varchar(10) not null,
    primary key(ID)
);
show tables;
desc my_table_new;
